# Use tech_user/secret as user/password credentials
version: '3'

volumes:
  mongo-volume: 
    driver: local
  formio-volume:
    driver: local
  db-volume:
    driver: local
  bonita-volume:
    driver: local

services:
  node:
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./btf/:/home/node/app
    ports:
      - 10631:10631
    command: "npm start"

  db:
    image: postgres:9.3
    environment:
      POSTGRES_PASSWORD: example
    command:
      - -c
      - max_prepared_transactions=100
    volumes:
      - db-volume:/var/lib/postgresql/data

  mongodb:
    image: mongo
    volumes:
      - mongo-volume:/data/db

  formio-api:
    image: skarvelis/formio-api:1.0
    ports:
      - 3001:3001
      - 8080:8080
    environment:
      - VIRTUAL_HOST=147.102.4.106:3001
      - REVERSE_PROXY=false
      - DB_HOST=mongodb
      - DB_NAME=formio
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASS=password
    depends_on:
      - mongodb
    volumes:
      - formio-volume:/app

  desktop:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - 6080:80
      - 5900:5900
      - 10000:8080
    environment: 
      - VNC_PASSWORD=str0ngpass
      - USER=etsoft 
      - PASSWORD=str0ngerpassw0rd
    volumes:
      - ./bondesktop/:/home/etsoft

  bonita:
    image: bonita
    ports:
      - 9090:8080
    environment:
      - POSTGRES_ENV_POSTGRES_PASSWORD=example
      - DB_VENDOR=postgres
      - DB_HOST=db
      - TENANT_LOGIN=tech_user
      - TENANT_PASSWORD=secret
      - PLATFORM_LOGIN=pfadmin
      - PLATFORM_PASSWORD=pfsecret
      - HTTP_API=true
    depends_on:
      - db
    volumes:
      - bonita-volume:/opt/bonita
    entrypoint:
      - bash
      - -c
      - |
        set -e
        echo 'Waiting for Postgres to be available'
        export PGPASSWORD="$$POSTGRES_ENV_POSTGRES_PASSWORD"
        maxTries=10
        while [ "$$maxTries" -gt 0 ] && ! psql -h "$$DB_HOST" -U 'postgres' -c '\l'; do
            sleep 1
        done
        echo
        if [ "$$maxTries" -le 0 ]; then
            echo >&2 'error: unable to contact Postgres after 10 tries'
            exit 1
        fi
        exec /opt/files/startup.sh

